// 引入 codemirror 所有语言包
import "codemirror/mode/javascript/javascript";
import "codemirror/mode/css/css";
import "codemirror/mode/htmlmixed/htmlmixed";
import "codemirror/mode/vue/vue";
import "codemirror/mode/markdown/markdown";
import "codemirror/mode/jsx/jsx";
import "codemirror/mode/sass/sass";
import "codemirror/mode/php/php";
import "codemirror/mode/python/python";
import "codemirror/mode/go/go";
import "codemirror/mode/ruby/ruby";
import "codemirror/mode/sql/sql";
// yaml
import "codemirror/mode/yaml/yaml";

// java
import "codemirror/mode/clike/clike";
// go
import "codemirror/mode/go/go";
// php
import "codemirror/mode/php/php";
// python
import "codemirror/mode/python/python";
// ruby
import "codemirror/mode/ruby/ruby";
// sql
import "codemirror/mode/sql/sql";
// shell
import "codemirror/mode/shell/shell";
