export const THEME_OPTIONS = [
  { label: "default", value: "default", filePath: "" },
  {
    label: "3024-day",
    value: "3024-day",
    filePath: "codemirror/theme/3024-day.css",
  },
  {
    label: "3024-night",
    value: "3024-night",
    filePath: "codemirror/theme/3024-night.css",
  },
  { label: "abbott", value: "abbott", filePath: "codemirror/theme/abbott.css" },
  { label: "abcdef", value: "abcdef", filePath: "codemirror/theme/abcdef.css" },
  {
    label: "ambiance",
    value: "ambiance",
    filePath: "codemirror/theme/ambiance.css",
  },
  {
    label: "ayu-dark",
    value: "ayu-dark",
    filePath: "codemirror/theme/ayu-dark.css",
  },
  {
    label: "ayu-mirage",
    value: "ayu-mirage",
    filePath: "codemirror/theme/ayu-mirage.css",
  },
  {
    label: "base16-dark",
    value: "base16-dark",
    filePath: "codemirror/theme/base16-dark.css",
  },
  {
    label: "base16-light",
    value: "base16-light",
    filePath: "codemirror/theme/base16-light.css",
  },
  { label: "bespin", value: "bespin", filePath: "codemirror/theme/bespin.css" },
  {
    label: "blackboard",
    value: "blackboard",
    filePath: "codemirror/theme/blackboard.css",
  },
  { label: "cobalt", value: "cobalt", filePath: "codemirror/theme/cobalt.css" },
  {
    label: "colorforth",
    value: "colorforth",
    filePath: "codemirror/theme/colorforth.css",
  },
  {
    label: "darcula",
    value: "darcula",
    filePath: "codemirror/theme/darcula.css",
  },
  {
    label: "dracula",
    value: "dracula",
    filePath: "codemirror/theme/dracula.css",
  },
  {
    label: "duotone-dark",
    value: "duotone-dark",
    filePath: "codemirror/theme/duotone-dark.css",
  },
  {
    label: "duotone-light",
    value: "duotone-light",
    filePath: "codemirror/theme/duotone-light.css",
  },
  {
    label: "eclipse",
    value: "eclipse",
    filePath: "codemirror/theme/eclipse.css",
  },
  {
    label: "elegant",
    value: "elegant",
    filePath: "codemirror/theme/elegant.css",
  },
  {
    label: "erlang-dark",
    value: "erlang-dark",
    filePath: "codemirror/theme/erlang-dark.css",
  },
  {
    label: "gruvbox-dark",
    value: "gruvbox-dark",
    filePath: "codemirror/theme/gruvbox-dark.css",
  },
  {
    label: "hopscotch",
    value: "hopscotch",
    filePath: "codemirror/theme/hopscotch.css",
  },
  {
    label: "icecoder",
    value: "icecoder",
    filePath: "codemirror/theme/icecoder.css",
  },
  { label: "idea", value: "idea", filePath: "codemirror/theme/idea.css" },
  {
    label: "isotope",
    value: "isotope",
    filePath: "codemirror/theme/isotope.css",
  },
  { label: "juejin", value: "juejin", filePath: "codemirror/theme/juejin.css" },
  {
    label: "lesser-dark",
    value: "lesser-dark",
    filePath: "codemirror/theme/lesser-dark.css",
  },
  {
    label: "liquibyte",
    value: "liquibyte",
    filePath: "codemirror/theme/liquibyte.css",
  },
  {
    label: "lucario",
    value: "lucario",
    filePath: "codemirror/theme/lucario.css",
  },
  {
    label: "material",
    value: "material",
    filePath: "codemirror/theme/material.css",
  },
  {
    label: "material-darker",
    value: "material-darker",
    filePath: "codemirror/theme/material-darker.css",
  },
  {
    label: "material-palenight",
    value: "material-palenight",
    filePath: "codemirror/theme/material-palenight.css",
  },
  {
    label: "material-ocean",
    value: "material-ocean",
    filePath: "codemirror/theme/material-ocean.css",
  },
  { label: "mbo", value: "mbo", filePath: "codemirror/theme/mbo.css" },
  {
    label: "mdn-like",
    value: "mdn-like",
    filePath: "codemirror/theme/mdn-like.css",
  },
  {
    label: "midnight",
    value: "midnight",
    filePath: "codemirror/theme/midnight.css",
  },
  {
    label: "monokai",
    value: "monokai",
    filePath: "codemirror/theme/monokai.css",
  },
  { label: "moxer", value: "moxer", filePath: "codemirror/theme/moxer.css" },
  { label: "neat", value: "neat", filePath: "codemirror/theme/neat.css" },
  { label: "neo", value: "neo", filePath: "codemirror/theme/neo.css" },
  { label: "night", value: "night", filePath: "codemirror/theme/night.css" },
  { label: "nord", value: "nord", filePath: "codemirror/theme/nord.css" },
  {
    label: "oceanic-next",
    value: "oceanic-next",
    filePath: "codemirror/theme/oceanic-next.css",
  },
  {
    label: "panda-syntax",
    value: "panda-syntax",
    filePath: "codemirror/theme/panda-syntax.css",
  },
  {
    label: "paraiso-dark",
    value: "paraiso-dark",
    filePath: "codemirror/theme/paraiso-dark.css",
  },
  {
    label: "paraiso-light",
    value: "paraiso-light",
    filePath: "codemirror/theme/paraiso-light.css",
  },
  {
    label: "pastel-on-dark",
    value: "pastel-on-dark",
    filePath: "codemirror/theme/pastel-on-dark.css",
  },
  {
    label: "railscasts",
    value: "railscasts",
    filePath: "codemirror/theme/railscasts.css",
  },
  {
    label: "rubyblue",
    value: "rubyblue",
    filePath: "codemirror/theme/rubyblue.css",
  },
  { label: "seti", value: "seti", filePath: "codemirror/theme/seti.css" },
  {
    label: "shadowfox",
    value: "shadowfox",
    filePath: "codemirror/theme/shadowfox.css",
  },
  {
    label: "solarized dark",
    value: "solarized dark",
    filePath: "codemirror/theme/solarized.css",
  },
  {
    label: "solarized light",
    value: "solarized light",
    filePath: "codemirror/theme/solarized.css",
  },
  {
    label: "the-matrix",
    value: "the-matrix",
    filePath: "codemirror/theme/the-matrix.css",
  },
  {
    label: "tomorrow-night-bright",
    value: "tomorrow-night-bright",
    filePath: "codemirror/theme/tomorrow-night-bright.css",
  },
  {
    label: "tomorrow-night-eighties",
    value: "tomorrow-night-eighties",
    filePath: "codemirror/theme/tomorrow-night-eighties.css",
  },
  { label: "ttcn", value: "ttcn", filePath: "codemirror/theme/ttcn.css" },
  {
    label: "twilight",
    value: "twilight",
    filePath: "codemirror/theme/twilight.css",
  },
  {
    label: "vibrant-ink",
    value: "vibrant-ink",
    filePath: "codemirror/theme/vibrant-ink.css",
  },
  {
    label: "xq-dark",
    value: "xq-dark",
    filePath: "codemirror/theme/xq-dark.css",
  },
  {
    label: "xq-light",
    value: "xq-light",
    filePath: "codemirror/theme/xq-light.css",
  },
  { label: "yeti", value: "yeti", filePath: "codemirror/theme/yeti.css" },
  { label: "yonce", value: "yonce", filePath: "codemirror/theme/yonce.css" },
  {
    label: "zenburn",
    value: "zenburn",
    filePath: "codemirror/theme/zenburn.css",
  },
];
